### ISSUE TITLE
EWIS-IF - new admonitions

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-mbxif#8]
There are a couple of block types in EWIS-IF AP242_Electrical_Harness_Tutorial_XML:
- recommendation, which is currently  encoded using non-existing `[RECOMMENDATION]` annotation;
![image](https://github.com/metanorma/mn-samples-mbxif/assets/55683568/9ff62c7a-e12d-4592-88ce-2a983b6ec70b)
- attention, which is currently  encoded using non-existing `[ATTENTION]` annotation;
![image](https://github.com/metanorma/mn-samples-mbxif/assets/55683568/df1bc284-7d1b-4c9a-a58a-2eecebee1938)
- unnamed, which is currently encoded using the existing `[IMPORTANT]` annotation.
![image](https://github.com/metanorma/mn-samples-mbxif/assets/55683568/bf312602-4ee0-45ce-8ca5-ebdb6bbd54fa)

We should probably add support for `RECOMMENDATION` and `ATTENTION` keywords and agree on how to treat the unnamed blocks.

**Comment by opoudjis** [comment]
The point of this flavour is that it be as lightweight as possible, so this task becomes encoding possible admonition keywords in metanorma-generic config.

**Comment by opoudjis** [comment]
Open-ended admonition types are already supported, by adding a type attribute to any pre-defined admonition type. So:

````
[CAUTION,type=attention]
====
Do not use...
====
````

The unnamed admonition can be named any type we want: leaving out the label is going to be a rendering type. But if we give it an empty type, 

````
[CAUTION,type=""]
====
Do not use...
====
````

we get Presentation XML:

````
<admonition id="_16b97ad5-3535-4a54-97e1-758fe59bc21e" type="">
<p id="_36496f0e-b521-ec1e-340f-51151c409df2">Do not use…<200b></p>
</admonition>
````

metanorma-generic is not currently prefixing admonitions with their type at all in rendering, checking why.

**Comment by opoudjis** [comment]
Ah, it's because we need to define i18n for the admonition types, which is config. If we don't define a type, which we won't for the empty type string, then no label is inserted. So the rendering of this is all configurable. Closing.

**Comment by anermina** [comment]
Thanks @opoudjis ! I was sure there was a way to encode this, but did not look into ISO documentation, but rather general Metanorma documentation. I have overlooked that this is NIST flavor which therefore relies on ISO.

**Comment by opoudjis** [comment]
In fact, this is generic Metanorma functionality, but shrug... :)
